server:
  # 配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  profiles:
    active: @profiles.active@
    include: async,config,url
  application:
      name: utour-user
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    #上传文件配置
    multipart:
      #单个文件大小20M（单位字节）
      max-file-size: 20480000
      #总数据大小100M（单位字节）
      max-request-size: 102400000
      enabled: true
      file-size-threshold: 0
      resolve-lazily: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    dbcp2:
      pool-prepared-statements: true

  #Redis
  redis:
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 10
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 10
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 10
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
        #空闲链接检测线程检测周期。如果为负值，表示不运行检测线程。（单位：毫秒，默认为-1）
        time-between-eviction-runs: 20000

  #rabbitmq相关配置
  rabbitmq:
    #并发量的配置
    listener:
      simple:
        #并发消费者的初始化值
        concurrency: 10
        #并发消费者的最大值
        max-concurrency: 20
        #每个消费者每次监听时可拉取处理的消息数量
        prefetch: 5

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.coupon.entity.*
management:
  health:
    rabbit:
      enabled: false

logging:
  level:
    com.coupon.mapper: debug
