server:
  port: 8480
spring:
  datasource:
    dynamic:      # 多数据源 读写分离
      read:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://10.168.1.109:3306/pf_coupon?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: ylh
        password: Ylh16888test
        name: pf_coupon
      write:
        url: jdbc:mysql://10.168.1.109:3306/pf_groupwork?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: ylh
        password: Ylh16888test
        name: pf_groupwork
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis
  redis:
    host: 10.168.1.111
    #端口号
    port: 6379
    #密码
    password: Ylh16888
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 10000
    # Redis数据库索引（默认为0）
    database: 0
    instanceid: crs-9qkg3m10

  #rabbitmq相关配置
  rabbitmq:
    host: 10.168.1.38
    port: 5672
    username: pf_coupon
    password: yuelvhui
    virtual-host: pf_coupon



request:
  domain:
    message: http://gateway.yueshang.shop/message/v2
    common: http://10.168.2.25:8180
    permissions: http://gateway.yueshang.shop/permission/v1

ziying:
  sortUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryCategory
  productUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryYcLoudProductList
  skuUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryProductSku
  pms:
    appKey: pms
    appSecret: 80e9fc22001cd7b0808ebebb9aee76d6
    account: 14

memberCenter:
  syncCoupon: http://10.168.1.228:8380/coupon/operation
  batchOnline: http://10.168.1.228:8380/coupon/invalidCoupons

goodsCenter:
  goodsUrl: https://gateway.yueshang.shop/mall/v1/middle/queryProductList

noticeUrl:
  ljt:
    groupNoticeUrl: https://gateway.yueshang.shop/mall/v1/api/combination/syncCombinationStatus
    activityNoticeUrl: https://gateway.yueshang.shop/mall/v1/api/combination/syncOfflineCombination