server:
  port: 8780
spring:
  datasource:
    coupon:
      name: pf_coupon
      jdbc-url: jdbc:mysql://172.21.0.33:3306/pf_coupon_test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: utest
      password: UTest@2021
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      dbcp2:
        pool-prepared-statements: true
    group:
      jdbc-url: jdbc:mysql://172.21.0.33:3306/pf_groupwork?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: dba%3u072knm4
      name: pf_groupwork
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      dbcp2:
        pool-prepared-statements: true

  #Redis
  redis:
    host: 172.21.0.21
    #端口号
    port: 6379
    #密码
    password: rds%add7282es
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 10000
    # Redis数据库索引（默认为0）
    database: 0
    instanceid: crs-9qkg3m10

  #rabbitmq相关配置
  rabbitmq:
    host: 172.21.0.37
    port: 5672
    username: test_pf_coupon
    password: yuelvhui
    virtual-host: test_pf_coupon

request:
  domain:
    message: http://test-gateway.yueshang.shop/message
    common: http://test-gateway.yueshang.shop/common
    permissions: https://gateway.yueshang.shop/permission/v2

ziying:
  sortUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryCategory
  productUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryYcLoudProductList
  skuUrl: https://gateway.yueshang.shop/mall/v1/api/v1/queryProductSku
  pms:
    appKey: pms
    appSecret: 80e9fc22001cd7b0808ebebb9aee76d6
    account: 14

memberCenter:
  syncCoupon: http://test-gateway.yueshang.shop/member/v1/coupon/operation
  batchOnline: http://test-gateway.yueshang.shop/member/v1/coupon/invalidCoupons

goodsCenter:
  goodsUrl: https://gateway.yueshang.shop/mall/v1/middle/queryProductList

noticeUrl:
  ljt: 
    groupNoticeUrl: https://gateway.yueshang.shop/mall/v1/api/combination/syncCombinationStatus
    activityNoticeUrl: https://gateway.yueshang.shop/mall/v1/api/combination/syncOfflineCombination